[package]
name = "QR_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = "1.0.1"
generic-matrix = "0.2.2"
reed-solomon-erasure = "6.0.0"
